name: Python package

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
         python-version: '3.x'
      - name: Install dependencies
        run: |
         pip install pytest
         pip install pytest-cov
         python -m pip install django
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         pytest backend/dinesmart/tests.py
         
  deploy:
    - uses: actions/checkout@v2
    - name: Django aws eb deployment
      uses: joel-hanson/django-aws-eb-deploy@V1.1
      with:
        python_version: '3.x'
        flake8: true
        aws_access_key_id: ${{ secrets.aws_access_key_id }}
        aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
        django_path: backend
        unit_testing: true
        deploy: true
        min_coverage: 10
        security_check: true
        flake8_config_file: "backend/.flake8"

