name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --prefix /home/runner/work/Group-A7/Group-A7/frontend
      - run: CI=false npm run build --if-present --prefix /home/runner/work/Group-A7/Group-A7/frontend
      - run: npm test --prefix /home/runner/work/Group-A7/Group-A7/frontend
    
      #- name: Upload coverage to Codecov
      #  uses: codecov/codecov-action@v1
       # with:
        #  token: ${{ secrets.CODECOV_TOKEN }}